Moaguide-develop/moaguide_front

src/components/signup/Step1.tsx

fix: step1

---

src/app/signup/page.tsx
src/components/signup/Step1.tsx

fix: lint error

---

src/app/page.tsx
src/app/product/detail/[id]/page.tsx
src/app/product/page.tsx
src/components/product/Dividend.tsx
src/components/product/Filter.tsx
src/components/product/Product.tsx
src/components/product/ProductList.tsx
src/components/product/ProductPagenation.tsx
src/components/product/ProductSort.tsx
src/components/product/Report.tsx
src/components/product/TopProduct.tsx
src/components/product/detail/News.tsx
src/components/product/detail/Notice.tsx
src/components/product/detail/Report.tsx
src/components/skeleton/NoticeItemSkeleton.tsx
src/factory/ProductDetail.ts
src/factory/useNewsList.ts
src/factory/useReportList.ts
src/types/Diviend.ts
src/types/ProductType.ts

Product 필터링 + detail api 연동

---

src/app/find/page.tsx
src/app/sign/page.tsx
src/app/signup/page.tsx
src/components/common/Navbar.tsx

fix: useSearchParams CSR 오류

---

src/app/newissue/page.tsx
src/app/page.tsx
src/app/product/page.tsx
src/app/reportpage/page.tsx
src/components/common/Navbar.tsx

기존 쿼리스트링으로 작업하던 페이지네이션 기능을 page 형식으로 수정하였습니다.
현재 로컬에서는 페이지 반응속도가 2-3초 => 0.5-1.5초 정도로 향상되었는데
배포환경에서는 어떻게 적용될지 몰라서 테스트 해보겠습니다.

fix:page 형식으로 nav바 변경

---

src/app/newissue/page.tsx
src/app/page.tsx
src/app/reportpage/page.tsx
src/components/common/Navbar.tsx

suspense가 UX를 해치는거 같아 삭제 처리했습니다.
그리고 테스트 결과 조각투자상품을 제외하고는 속도 정상적으로 처리되어서
조각투자상품부분만 좀더 확인해볼것 같습니다.

fix: suspense 제거

---

src/app/mypage/page.tsx
src/app/signup/page.tsx
src/components/find/FindEmail.tsx
src/components/find/FindPassword.tsx
src/components/find/FindTabs.tsx
src/components/signup/Step1.tsx
src/components/signup/Step3.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/PhoneVerification.tsx

fix: 모바일 레이아웃 높이 재설정

---

src/app/signup/page.tsx
src/components/find/FindEmail.tsx
src/components/find/FindPassword.tsx
src/components/find/FindTabs.tsx
src/components/signup/Step1.tsx
src/components/signup/Step3.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/PhoneVerification.tsx

fix: 반응형 디자인 수정

---

src/components/signup/Step1.tsx
src/components/signup/Step3.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/PhoneVerification.tsx

design: 반응형 마무리 작업

---

src/components/find/FindEmail.tsx

fix: findemail 100dvh

---

src/app/mypage/edit/changepassword/page.tsx
src/app/mypage/edit/changephone/page.tsx
src/components/find/FindEmail.tsx
src/components/find/FindPassword.tsx
src/components/mypage/CertifyPassword.tsx
src/components/mypage/NewPassword.tsx
src/components/signup/Step1.tsx
src/components/signup/Step3.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/PhoneVerification.tsx

- 반응형 레이아웃 추가작업(마이페이지)
- 버튼 마진값 반응형 처리
- 회원가입 때 비밀번호 매칭 안맞는 오류 해결

fix: 반응형 레이아웃 작업 및 비밀번호 매칭 오류

---

src/app/mypage/edit/changepassword/page.tsx
src/app/mypage/edit/changephone/page.tsx
src/app/mypage/edit/page.tsx
src/components/signup/Step1.tsx

design: 비밀번호변경페이지, 휴대폰번호변경페이지 레이아웃깨지는 문제 해결

---

package.json
src/components/mypage/CertifyPassword.tsx
src/components/sign/SignLayout.tsx
src/service/auth.ts
src/service/axiosInstance.ts
src/type/cookies.ts
src/utils/cookie.ts
yarn.lock

close #31 
- 어세스토큰이 만료되면 리프레시토큰을 활용해 다시 토큰을 요청하는 기능을 구현하였습니다.
- 리프레시토큰 적용
- 버튼 마진값 통일 및 버튼 색상 통일

feat: 리프레시토큰 적용

---

src/app/page.tsx
src/app/signup/page.tsx
src/components/sign/SignLayout.tsx
src/service/auth.ts

feat: 네이버 소셜로그인 작업

---

src/components/sign/GoogleLogin.tsx
src/components/sign/KakaoLogin.tsx

fix: kakao, google 소셜로그인

---

src/app/mypage/edit/changepassword/page.tsx
src/app/mypage/edit/changephone/page.tsx
src/app/mypage/edit/page.tsx
src/app/mypage/page.tsx
src/app/practicepage/page.tsx
src/components/home/Guide.tsx
src/components/home/HomeFooter.tsx
src/components/home/Index.tsx
src/components/home/MainList.tsx
src/components/home/MainListItem.tsx
src/components/home/MainReport.tsx
src/components/home/MoblieRank.tsx
src/components/home/RealtimeRank.tsx
src/components/home/RecentlyIssue.tsx
src/components/home/SubMenu.tsx

- 메인페이지 반응형 디자인 작업
- 메인페이지 이미지 연결
- 마이페이지, 학습하기 페이지 반응형 디자인 작업

feat: 메인페이지

---

src/components/home/IssueItem.tsx
src/components/home/MainListItem.tsx

feat: 메인페이지 주요 상품 현황 링크 연결

---

src/components/home/MainReport.tsx
src/components/home/MainReportItem.tsx
src/types/homeComponentsType.ts

feat: 실력 올리기 링크 연결

---

src/components/common/Container.tsx
src/components/recentlyIssue/BestNews.tsx
src/components/recentlyIssue/BestNewsItem.tsx
src/components/recentlyIssue/CategoryNews.tsx
src/components/recentlyIssue/CategoryNewsItem.tsx
src/types/homeComponentsType.ts

- 최신이슈탭 이미지 연결 작업
- 최신이슈탭 반응형 디자인

feat: 최신이슈 페이지

---

.github/workflows/cd-aws.yml
.github/workflows/ci-aws.yml
Dockerfile
src/components/product/Product.tsx
src/components/product/ProductClassification.tsx
src/components/product/ProductDealContentList.tsx
src/components/product/ProductEndRecruitmentContentList.tsx
src/components/product/ProductIsdealSort.tsx
src/components/product/ProductMobilePagenation.tsx
src/components/product/ProductPagenation.tsx
src/components/product/ProductRecruitmentContentList.tsx
src/components/product/detail/art/ArtProfit.tsx
src/components/product/detail/building/BuildingProfit.tsx
src/components/product/detail/building/PublicTransport.tsx
src/components/product/detail/building/chart/CopyrightFeeChart.tsx
src/components/product/detail/building/chart/FloatingPopulationChart.tsx
src/components/product/detail/content/ContentProfit.tsx
src/components/product/detail/content/MovieChart.tsx
src/components/product/detail/content/MovieStats.tsx
src/components/product/detail/content/MovieTenChart.tsx
src/components/product/detail/cow/CowMarketChart.tsx
src/components/product/detail/cow/CowPriceChart.tsx
src/components/product/detail/cow/CowProductDetail.tsx
src/components/product/detail/cow/CowProfit.tsx
src/components/product/detail/music/MusicProfit.tsx
src/components/product/detail/music/MusicYoutube.tsx
src/components/product/detail/music/chart/MusicCopyrightFee.tsx
src/components/product/detail/music/chart/YoutubeSearchChart.tsx
src/components/product/detail/music/chart/YoutubeViewChart.tsx
tailwind.config.ts

2차 배포 테스트 + AWS EC2 DOCKER 배포 환경 구성

---

src/components/practice/CategoryPractice.tsx
src/components/signup/Step1.tsx

remove: 14세 이상 동의부분 삭제

---

src/app/mypage/edit/changephone/page.tsx
src/app/mypage/edit/page.tsx
src/app/page.tsx
src/app/payment/check/confirm/success/page.tsx
src/app/signup/page.tsx
src/components/education/RoadMapItem.tsx
src/components/find/FindEmail.tsx
src/components/find/FindPassword.tsx
src/components/practice/CategoryPracticeItem.tsx
src/components/practice/CategorySubloadmapBottomArticle.tsx
src/components/product/Dividend.tsx
src/components/product/ProductClassification.tsx
src/components/recentlyIssue/BestNews.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/PhoneVerification.tsx
src/factory/ReportIssue.ts
src/factory/ReportLists.ts
src/factory/useNewsList.ts
src/service/auth.ts
src/service/change.ts
src/utils/localStorage.ts

remove: console log 제거

---

src/components/home/Guide.tsx
src/components/home/MainReport.tsx
src/components/practice/PracticeIndex.tsx

feat: 메인 배너 2개 및 학습하기 탭 배너 클릭 시, 네이버프리미엄 콘텐츠 이동

---

src/components/home/MainReport.tsx
src/components/practice/PracticeIndex.tsx

feat: 베너 커서 포인터

---

src/components/product/Bookmark.tsx

fix: conflict 해결

---

src/app/mypage/alarm/page.tsx
src/components/mypage/MypageHeader.tsx
src/components/mypage/MypageMenu.tsx

- 알림페이지 레이아웃
- 마이페이지 닉네임 부분 마진값

feat: 알림페이지 레이아웃

---

src/components/alarm/AlarmItem.tsx
src/components/home/Guide.tsx
src/components/skeleton/NotificationSkeleton.tsx

fix: build, lint 에러

---

src/components/alarm/AlarmItem.tsx

feat: 알림 클릭 시, 알림 삭제 api 요청 후 알림 api

---

src/app/mypage/alarm/page.tsx
src/app/page.tsx
src/components/alarm/AlarmItem.tsx
src/components/home/IssueItem.tsx
src/components/home/MainReport.tsx
src/components/home/MainReportItem.tsx
src/components/skeleton/IssueItemSkeleton.tsx
src/service/auth.ts
src/store/user.store.ts

- 알림페이지 알림 없을 때 텍스트 렌더링
- 메인 이슈 부분 데이터 및 스켈레톤 UI 반응형 디자인 재작업
- 메인 실력올리기 category값 제거
- 로그인 시 marketing 값 저장
- 마이페이지 > 알림 설정 페이지 marketing 값에 따른 토글 on/off
- 알림 설정 patch api 연결

feat: 알림 설정 페이지

---

src/components/home/MainList.tsx
src/components/home/MainListItem.tsx
src/factory/MainProduct.ts
src/types/homeComponentsType.ts

- 메인페이지 주요 상품 북마크 여부에 따라 아이콘 렌더링
- 메인페이지 주요 상품 북마크 추가 및 삭제 기능 구현 및 추가, 삭제 시에만 api 재호출
- 북마크 추가, 삭제 시 마이페이지 북마크 개수 api 재호출

feat: 메인페이지 북마크 기능

---

src/components/product/detail/content/ContentProfit.tsx
src/components/product/detail/cow/CowProfit.tsx

fix: build fix

---

src/app/globals.css
src/components/sign/SignLayout.tsx

design: 네이버 로그인 버튼 숨김 및 체크박스 버튼 디자인

---

src/components/home/MainList.tsx
src/components/home/MainListItem.tsx
src/components/signup/Step1.tsx
src/components/signup/Step3.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/EmailVerification.tsx
src/factory/MainProduct.ts

- 메인페이지의 주요상품현황 탭의 북마크 아이콘을 북마크 여부에 따라 렌더링하는데, 로그인 후에 처음 메인페이지 접속 시, 전체탭에 북마크된 상품이 있어도 북마크된 아이콘이 나오지 않는 문제 해결
- 전체탭에서 북마크 시, 다른탭의 동일한 데이터가 뜨는 카테고리의 캐시를 무효화해서 북마크시에만 api를 재호출 & 특정 카테고리에서 북마크 시, 전체탭의 캐시만 무효화해서 전체탭의 api만 재호출

fix: 메인 주요상품현황 북마크

---

src/utils/localStorage.ts

fix: 토큰 유효 시간 설정

---

src/components/product/detail/building/chart/CommercialRentChart.tsx
src/components/product/detail/building/chart/CommercialVacancyRateChart.tsx
src/components/product/detail/building/chart/CopyrightFeeChart.tsx
src/components/product/detail/building/chart/FloatingPopulationChart.tsx
src/components/product/detail/building/chart/OfficialPriceChart.tsx
src/components/product/detail/building/chart/StockPriceChart.tsx
src/components/product/detail/cow/CowMarketChart.tsx
src/components/product/detail/cow/CowPriceChart.tsx
src/components/product/detail/music/chart/MusicCopyrightFee.tsx
src/components/product/detail/music/chart/MusicStockPriceChart.tsx
src/components/product/detail/music/chart/YoutubeSearchChart.tsx

fix: 누락된 옵셔널 체이닝 추가

---

src/components/find/FindPassword.tsx
src/components/mypage/NewPassword.tsx
src/service/change.ts
src/utils/localStorage.ts

fix: verify token

---

src/components/home/MainListItem.tsx

feat: 메인페이지 북마크 알랄트 상세페이지랑 동일하게 맞추기

---

src/components/product/Dividend.tsx
src/components/product/TopProduct.tsx
src/components/product/detail/music/chart/YoutubeStreamingChart.tsx
src/types/MusicProductType.ts

fix: youtubeStreaminChart api 수정

---

src/components/product/detail/building/chart/StockPriceChart.tsx
src/components/product/detail/music/chart/MusicStockPriceChart.tsx
src/types/MusicProductType.ts

fix: 주가 max min 재설정

---

src/components/signup/Step1.tsx

fix: 마케팅수신동의 값 변경

---

src/app/layout.tsx

feat: og graph image

---

src/app/layout.tsx
src/app/robots.ts

fix: og graph 사진 수정

---

src/components/product/contentlist/ProductDealContentList.tsx
src/factory/ViewCount.ts

feat: 조회수 추가 api 로직 개발발

---

.env.production
src/components/find/FindPassword.tsx
src/components/find/FindTabs.tsx
src/components/signup/Step1.tsx
src/components/signup/Step3.tsx
src/components/signup/Step4.tsx
src/components/signup/modal/EmailVerification.tsx

design: 회원가입 레이아웃

---

src/app/mypage/notice/[id]/page.tsx
src/app/mypage/notice/page.tsx
src/components/signup/Step1.tsx
src/components/signup/modal/AgeModal.tsx
src/components/signup/modal/MarketingModal.tsx
src/components/signup/modal/PrivacyControllModal.tsx
src/components/signup/modal/PrivacyModal.tsx
src/components/signup/modal/ServiceControllModal.tsx
src/components/signup/modal/ServiceModal.tsx

design: 이미지 프리렌더링

---

src/components/modal/Quitmodal.tsx
src/service/change.ts

fix: ci lint error

---

src/components/modal/Quitmodal.tsx

fix: 회원탈퇴 모달 외부 클릭 금지

---

src/components/modal/Quitmodal.tsx

design: 모달 크기

---

src/lib/NaverAnalytics.tsx

fix: 네이버 애널리틱스 빌드 error

---

src/components/home/IssueItem.tsx
src/components/home/MainListItem.tsx
src/components/product/contentlist/ProductBookmarkContentList.tsx
src/components/recentlyIssue/BestNews.tsx
src/components/recentlyIssue/BestNewsItem.tsx
src/components/recentlyIssue/CategoryNewsItem.tsx
src/factory/ViewCount.ts
src/utils/cookies.ts

- 메인페이지 상품 현황, 최신이슈 및 마이페이지 북마크 내 상품 조회수 api 연결
- 가장 많이 본 뉴스 기본 이미지 처리

fix: 테스트 QA

---

src/components/recentlyIssue/BestNewsItem.tsx

fix: 베스트 뉴스 이미지

---

src/app/page.tsx
src/components/sign/GoogleLogin.tsx

fix:  소셜로그인 access_token 만료시간 설정

---

src/app/mypage/page.tsx
src/components/common/Gnb.tsx

fix: Gnb, 마이페이지 토큰 재발급 로직

---

src/app/mypage/page.tsx
src/components/common/Gnb.tsx
src/utils/localStorage.ts

fix: 토큰 관리

---

src/components/home/MainReport.tsx

fix: 메인페이지 실력올리기 부분 배너 모바일 클릭

---

src/app/mypage/alarm/page.tsx

design: 알림 여부에 따라 알랄트 메시지

---

src/app/globals.css
src/components/find/FindPassword.tsx
src/components/signup/modal/EmailVerification.tsx
src/components/signup/modal/LoadingSpinner.tsx

fix: 이메일 인증 로딩스피너

---

src/app/layout.tsx

test: 구글서치콘솔 인가

---

src/app/layout.tsx

feat: naver site verification

---

src/app/quiz/test/page.tsx
src/app/signup/page.tsx

- 퀴즈페이지 이탈 시, 퀴즈제출 api 호출 후 이탈
- 이탈 방지 문구 및 퀴즈 시간 디자인
- 회원가입 페이지 이탈 시, 기본 브라우저 경고문구 추가

feat: 퀴즈풀기 페이지

---

src/app/quiz/finish/page.tsx
src/app/quiz/test/page.tsx
src/factory/Quiz/QuizScore.ts

- 퀴즈페이지 및 퀴즈결과페이지 비로그인 접근 불가
- 퀴즈 점수 get api 연동
- 퀴즈페이지 유저정보 input값 제거 후 세션스토리지에서 받아오기
- 퀴즈페이지 및 퀴즈결과페이지 비로그인 접근 불가
- 퀴즈 점수 get api 연동
- 퀴즈페이지 유저정보 input값 제거 후 세션스토리지에서 받아오기
- 퀴즈결과페이지 로딩 스켈레톤
- 퀴즈결과페이지 세션스토리지값 제거

feat: 퀴즈페이지 수정

---

src/app/quiz/finish/page.tsx

close #144 
- build error - sessiongStorage 클라이언트 측에서만 실행

fix: build error - sessiongStorage 클라이언트 측에서만 실행

---

src/app/quiz/test/page.tsx

fix: 퀴즈페이지 에러 헨들링

---

src/app/quiz/test/page.tsx

fix: 퀴즈 뒤로가기 오류 수정

---

src/app/quiz/finish/page.tsx

fix: 퀴즈 결과 페이지 버튼 위치 조정

---

src/app/quiz/finish/page.tsx
src/app/quiz/test/page.tsx

fix: 모바일 스크롤 이동되는 현상 수정

---

src/app/plugin.ts
src/app/product/detail/building/[id]/page.tsx
src/app/product/detail/layout.tsx
src/app/product/detail/music/[id]/page.tsx
src/components/product/Dividend.tsx
src/components/product/Product.tsx
src/components/product/detail/building/Map.tsx
src/components/product/detail/building/chart/AccommodationRateChart.tsx
src/components/product/detail/building/chart/CommercialRentChart.tsx
src/components/product/detail/building/chart/CommercialVacancyRateChart.tsx
src/components/product/detail/building/chart/CopyrightFeeChart.tsx
src/components/product/detail/music/chart/MusicCopyrightFee.tsx
src/types/cookies.ts

Refactoring

---

src/components/product/detail/music/MusicProductDetail.tsx
src/components/product/detail/music/chart/YoutubeStreamingChart.tsx
src/components/product/detail/music/chart/YoutubeViewChart.tsx

fix: 뮤직 상세 텍스트 제거 및 수정

---

src/components/product/detail/building/BuildingProfit.tsx
src/components/product/detail/music/MusicProfit.tsx

fix: 빌딩/음악 상세 페이지 (배당/저작권료) 지급일 -> (배당/저작권료) 기준일로 수정

---

src/utils/localStorage.ts

fix: 토큰 유지 시간 증가

---

src/app/learning/detail/[articleId]/page.tsx
src/components/learning/FilteredContents.tsx
src/components/learning/LatestNewsClipping.tsx
src/components/learning/LearningPageClient.tsx
src/components/learning/PopularContents.tsx
src/components/learning/RecentContents.tsx
src/components/learning/article/ArticleDetailClientWrapper.tsx
src/components/learning/article/ArticleDetailContent.tsx
src/components/learning/article/ArticleDetailHeader.tsx
src/factory/Article/GetArticle.ts
src/types/filterArticle.ts
src/types/learning.ts

아티클 페이지 리뉴얼 작업
- 아티클 페이지 api 및 필터링 api data type 변경
- 아티클 상세정보 api 연동 및 레이아웃

feat: 아티클 페이지 리뉴얼 작업

---

src/app/learning/detail/[articleId]/page.tsx
src/components/learning/LearningPageClient.tsx
src/components/learning/article/ArticleDetailClientWrapper.tsx
src/components/learning/article/ArticleDetailContent.tsx
src/components/learning/article/BackButton.tsx
src/factory/Article/GetArticle.ts
src/types/learning.ts

- 아티클 상세페이지 무료/유료 컨텐츠 text, paywallUp 구분

feat: 아티클 상세페이지 무료/유료 컨텐츠 구분 로직

---

src/components/learning/article/RelatedArticles.tsx

관련 아티클 응답 api 형식 string으로 올 시, 처리

fix: 관련 아티클 예외처리

---

src/components/learning/LearningPageClient.tsx
src/components/learning/PopularContents.tsx
src/components/learning/article/ArticleDetailClientWrapper.tsx

fix: article detail access by token

---

src/components/learning/LearningPageClient.tsx

fix: article filter setCategory

---

src/components/learning/FilteredContents.tsx
src/components/learning/LatestNewsClipping.tsx
src/components/learning/LearningPageClient.tsx
src/components/learning/PopularContents.tsx
src/components/learning/RecentContents.tsx
src/components/learning/SubscriptionBanner.tsx
src/components/learning/article/ArticleDetailContent.tsx
src/components/learning/article/BackButton.tsx
src/components/skeleton/LatestNewsClippingSkeleton.tsx
src/components/skeleton/PopularContentsSkeleton.tsx

아티클 페이지 모바일 디자인 작업
- 카테고리값 null & 아티클, 영상 구분 탭 존재 할 때 탭 border-b 및 font-bold 적용
- 아티클 각 컴포넌트 모바일 뷰 렌더링 시, 이미지 내부에 아티클 type 적용
- 아티클 페이지 모바일 배너 작업
- 아티클 페이지 인기 컨텐츠 컴포넌트 모바일 뷰 w-full 적용

design : 아티클 페이지 모바일 디자인 디테일 작업

---

public/images/learning/article_liked_background.svg
src/components/learning/LatestNewsClipping.tsx
src/components/learning/LearningPageClient.tsx
src/components/learning/PopularContents.tsx
src/components/learning/RecentContents.tsx
src/components/learning/article/RelatedArticles.tsx
tailwind.config.ts

테일윈드 속성 추가 및 아티클 페이지 좋아요 백그라운드 이미지 설정

design : 테일윈드 속성 추가 및 아티클 페이지 좋아요 백그라운드 이미지 설정

---

src/components/learning/LearningPageClient.tsx

feat: image optimize by useMemo, window.Image()

---

src/components/learning/article/ArticleDetailContent.tsx
tailwind.config.ts

아티클 상세페이지 html parse 과정에서 max-w, left와 같은 스타일들이 적용되지 않는 문제를 해결

Fix: html parse max-w, left style setArrtibute

---

src/components/common/Navbar.tsx

fix: navbar router link change

---

src/components/common/MobileFooter.tsx
src/components/learning/FilteredContents.tsx
src/components/learning/ResponsivePagination.tsx

아티클 페이지 QA
- 아티클페이지 데스크탑 페이지네이션 개수 10개 고정
- 아티클 페이지 모바일 페이지네이션 개수 5개 고정
- 모바일 BottomNavBar 학습하기 아이콘 router 경로 변경
- 아키클페이지 컨텐츠 필터 시, Body Content break-all 속성 추가

Fix: QA Article Page

---

.github/workflows/ci-aws.yml

feat: tosspayments key  env 등록
